# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 631a346a586736442ae5408aada6345eee308412c7c69a46259a4ecd2542b5e50aa0d6347f7f200f21091ba2de8def515e7daac5c7f651e14e05fad3847340de

test:
  secret_key_base: d309eeac4f9bc08020b8e44eeee6c59187a9e06121760a8946e764320fcc912d2a778eb029dfbc3d33916e5ecf4c1c36cff8e09a14e7966a02a40e489a449416

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
